spring:
  application:
    name: ex07_mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_db?serverTimezone=Asia/Seoul
    username: root
    password: root
  sql:
    init:
      mode: always # 앱 구동 시 초기 스크립트 자동 실행

mybatis:
  configuration:
    map-underscore-to-camel-case: true # user_id -> userId
  type-aliases-package: com.example.mybatis.dto # com.example.mybatis.dto.User -> User
  # mapper-locations:
  # - mapper/user.xml
  #- mapper/post.xml
  mapper-locations: classpath:mapper/*.xml
